### ISSUE TITLE
Request: Java example

### ISSUE THREAD

**Issue by nimosunbit** [tylerlong/ringcentral-softphone-js#2]
Hey, can you provide a java example for the supervision of calls (server)?

**Comment by tylerlong** [comment]
Do you mean this article: https://medium.com/ringcentral-developers/automatically-supervise-your-call-agents-78c0cd7caf7f ?

Currently there is no (official) way to get real time phone call audio data in pure Java. 

Please tell me more about your use case and I may be able to help.

**Comment by nimosunbit** [comment]
Thanks for the fast reply. My mean is to connect with Java using WebSocket and to receive the audio and save it / transcript it.
Playing it in RT is not necessary.

**Comment by tylerlong** [comment]
WebSocket is only for SIP. Audio is transferred via WebRTC. You need a Java library which supports WebRTC. I don't know such a Java library.

It is possible with JavaScript because browsers support WebRTC out of box. And for node.js there is  https://github.com/node-webrtc/node-webrtc. For Java, I am not sure it is possible.

**Comment by tylerlong** [comment]
There is something for your consideration: https://medium.com/ringcentral-developers/search?q=pjsip

So PJSIP works with RingCentral. And PJSIP has a Java wrapper: https://www.pjsip.org/docs/book-latest/html/intro_pjsua2.html#using-in-java-application

Here is the code to save audio: https://github.com/ringcentral/ringcentral-pjsip/blob/master/demos/answer-and-save-to-wav-file.cpp

It is C++ code, I am afraid that I cannot help you with Java because I have no hands-on experience at all. PJSIP has Java wrapper so in theory you can translate the C++ code into Java (but it is still C++ underneath, if you want to "compile once, run everywhere" you also need to compile PJSIP C++ code everywhere).

**Comment by nimosunbit** [comment]
Great! can you add a demo for that? will help to many of us that use Kotlin and want to start using this amazing feature.

**Comment by tylerlong** [comment]
Close it since it is not closely related to this repository.

For those who need help with RingCentral's APIs/SDKs, please send email to devsupport@ringcentral.com
